version: '3.3'

services:
  rest-service:
    container_name: rest-service
    build: .
    networks: 
      - rest-database
    hostname: rest-service
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    ports:
      - 8010:8000
    depends_on:
      rest-db:
        condition: service_healthy

  rest-db:
    container_name: rest-db
    image: postgres:16
    networks: 
      - rest-database
    hostname: rest-db
    ports:
      - 5433:5432
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./db:/var/lib/postgresql/data

networks:
  rest-database:
